site_name: Manual de Supervivencia - BANG!
site_author: Ganandorf98
site_url: https://ganandorf98.github.io/proyectosri/

theme:
  name: material
  language: es
  palette:
    primary: deep orange
    accent: amber
  features:
    - search.highlight
    - navigation.tabs

nav:
  - Inicio: index.md
  - Roles y Objetivos: roles.md
  - Mecánica de Juego: fases.md
  - Guía de Cartas: cartas.md
  - Personajes: personajes.md
  - English Version:
      - Home: en/index.md
      - Roles: en/roles.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css